export const ASYNC_LOADING = 'ASYNC_LOADING';
export const ASYNC_ERROR = 'ASYNC_ERROR';
export const GET_CURRENT_SESSION = 'GET_CURRENT_SESSION';
export const GET_CURRENT_LOCATION = 'GET_CURRENT_LOCATION';
export const SET_CURRENT_LOCATION = 'SET_CURRENT_LOCATION';
export const SET_OPENMRS_LOCATION = 'SET_OPENMRS_LOCATION';
export const GET_LOGOUT_URL = 'GET_LOGOUT_URL';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
